services:
  - type: web
    name: rentaleze-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: DB_PATH
        value: /data/rentaleze.db
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
